[package]
name = "audio-sender"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
cpal = "0.15"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"

[[bin]]
name = "audio-sender"
path = "src/main.rs"